# Welcome to the Manhunt-Plugin developed by Mayhan
# This is the Configuration-File here u can change some Stuff

#Should all Players that are not  Operator be freezed on Startup.
freeze-on-start: true

#Should everyone die when one person dies.
team-death: true

#Should the plugin use custom Join- / Quit messages.
custom-messages: true

#Should all players be healed on start
heal-on-start: true

#Timer set 0 on start. 0 - 24000
time-set-on-start: 0

#Enable custom motd. Must be specified down below
enable-motd: false

#Set a motd when a player joins the server standard: "Welcome to the Server!"
custom-motd: