# Welcome to the Manhunt-Plugin developed by Mayhan
# This is the Configuration-File here u can change some Stuff

#Should all Players that are not  Operator be freezed on Startup.
freeze-on-start: true

#Should everyone die when one person dies.
team-death: true