name: Manhunt-Plugin
version: '${project.version}'
main: de.mayhan.challenge.Main
api-version: 1.19
commands:
  timer:
    usage: 'Usage: /timer <start | stop | pause | resume>'
    description: 'The Timer: Use /timer <start | stop | pause | resume>'
    permission: system.timer

  freeze:
    usage: 'Usage: /freeze - /fz'
    aliases:
      - 'fz'
    description: 'Freezes every player that inst Server-Operator.'
    permission: system.freeze

  unfreeze:
    usage: 'Ussage: /unfreeze - /ufz'
    aliases:
      - 'ufz'
    description: 'Unfreezes every player.'
    permission: system.freeze